///For App Icons fetched from www.fluttericons.com

/// Flutter icons AliahApp
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AliahApp
///      fonts:
///       - asset: fonts/AliahApp.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class AliahApp {
  AliahApp._();

  static const _kFontFam = 'AliahApp';

  static const IconData bookshelf = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData calendar = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData feedback = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData rupee = IconData(0xe804, fontFamily: _kFontFam);
  static const IconData web = IconData(0xe805, fontFamily: _kFontFam);
  static const IconData professor = IconData(0xe80d, fontFamily: _kFontFam);
}
